### ISSUE TITLE
listpost수정 확인해주세요

### ISSUE THREAD

**Issue by thiathat20** [thiathat20/OSS_project#10]
printpostlist()를 listpost()으로 쓰신거 같아서 수정 했어요
아마 제가 나중에 계정 CRUD함수를 추가하면서 함수이름을 이상하게 만들었나봐요 
일단 헤더를 기준으로 c파일을 수정 했는데 혹시 listpost가 나을거 같으면 헤더파일이랑 c파일 수정해 주세요

printpostlist로 하실꺼면 알려주세요 계정CRUD 함수명을 고쳐야 할거 같아요

- [x] printpostlist VS listpost 어떤거 쓸까요?

**Comment by patcha98** [comment]
postlist 로 해놓겠습니다

**Comment by patcha98** [comment]
postlist 라는 구조체 명이 이미 있어서 readpostlist 로 변경했습니다. 오류 모두 수정하였습니다.
