### ISSUE TITLE
포스트 저장 버그

### ISSUE THREAD

**Issue by thiathat20** [thiathat20/OSS_project#11]
- [x] 저장할때 삭제된 포스트 처리에 버그가 있음

(-1이 프린트 되고, 다음 게시글도 같이 삭제됨)

**Comment by patcha98** [comment]
확인 감사합니다. 함수 구현은 완료했으니 이번 주는 버그 및 에러를 잡고 위키랑 readme 조금 더 깔끔하게 수정하는 방향으로 작업하겠습니다~

**Comment by thiathat20** [comment]
함수 전부 구현 하신거 보고 깜짝 놀랐어요 버그는 잡았습니다
-1 체크 하는 부분에 i+1이 아니라 i가 있었네요
