### ISSUE TITLE
키워드 삭제 함수 구현하기

### ISSUE THREAD

**Issue by thiathat20** [thiathat20/OSS_project#13]
이거만 구현 하면 함수 구현은 끝인가요?

**Comment by patcha98** [comment]
키워드 검색이 있어서 굳이 키워드 삭제가 필요할까 해서 안 넣은건데 넣는게 좋을까요?

**Comment by thiathat20** [comment]
생각해 보니 그런거도 같네요
일단 처음 함수 정의할때 키워드 삭제가 있어서
검색이랑 삭제랑 짬뽕시켜서 구현해 봤어요
근데 중복되는 함수다 보니 아무래도 한번 정리를 하는게 좋을거 같...나요?
