### ISSUE TITLE
주석 정리 필요 할까요?

### ISSUE THREAD

**Issue by thiathat20** [thiathat20/OSS_project#14]
코드 보다가 문득 든 생각인데 시간이 되면 코드(중복, 주석)정리 해볼까요?

- [ ] 필요하다
- [ ] 굳이?

**Comment by patcha98** [comment]
하는게 깔끔할 듯한데 지금으로도 충분히 이해할 수 있는 정도가 아닌가 싶네요. 저의 입장은 반반입니다 ㅋㅋ
