### ISSUE TITLE
잘못된 입력에서 프로그램 종료

### ISSUE THREAD

**Issue by thiathat20** [thiathat20/OSS_project#16]
잘못된 입력을 받으면 프로그램이 종료되는 경우를 발견했는데 어떻게 하죠?
ex) 글 목록 보기(1) --> 번호선택에서 문자 입력 --> 프로그램 종료

**Comment by patcha98** [comment]
버그 수정해보겠습니다

**Comment by patcha98** [comment]
수정 완료 하였습니다
