### ISSUE TITLE
post_curd 만들어 주세요!

### ISSUE THREAD

**Issue by thiathat20** [thiathat20/OSS_project#8]
일단 계정 관련 CRUD는 제가 만들어 놓을게요(uesr_crud)
혹시 작업 하실때 post_CRUD부터 작업 하시면 될 거같아요!(post_crud)

**Comment by patcha98** [comment]
박훈성 post_crud.h / post_crud.c 구현

- [x] post_crud.h구현

- [x]  post_crud.c 구현

**Comment by patcha98** [comment]
이슈 하나 따로 생성할게요
